[package]
name = "gui_mqtt_client"
version = "0.1.0"
edition = "2018"

# For m1 macs only
# [build]
# target = "aarch64-apple-darwin"

[dependencies]
client= { path= "../client" }
gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git" }
