[package]
name = "clientDevice"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mqtt_packet = {path= "../mqtt_packet"}
client= { path= "../client" }

rand="0.8.4"